Hook registration with backend
CS-495-FALL-2024-TEAM-2/uactf-frontend pull request #45
Opened 2024-10-25 21:28 UTC by nhanaa

Updates:
- Add hooks to connect frontend with backend for registration.

2024-10-27 01:35 UTC, GoZaddy reviewed
Link to register as crimson defense member currently goes to /register/student instead of register/cd-member

2024-10-27 01:47 UTC, GoZaddy requested changes
- link to register as cd-member goes to /register/student
- backend returns a 400 status code when registering as cd-member (looks like the request body is missing username?) I'm also not sure why we need the competition id to create crimson defense member accounts but I'll talk to backend about that
- i'm also getting a cors issue when registering as teacher(will also talk to backend)

2024-10-27 21:28 UTC, GoZaddy commented on src/hooks/accounts.hooks.ts
> +      `${BASE_API_URI}/accounts/teacher/create`,
This should be `/accounts/teachers/create` (plural teachers instead of teacher)

2024-10-27 23:41 UTC, nhanaa commented
> * link to register as cd-member goes to /register/student
> * backend returns a 400 status code when registering as cd-member (looks like the request body is missing username?) I'm also not sure why we need the competition id to create crimson defense member accounts but I'll talk to backend about that
> * i'm also getting a cors issue when registering as teacher(will also talk to backend)

Yeah the backend also requires some changes which I made in a separate PR in the backend to work. They should be getting rid of competition id and username.

2024-10-28 00:36 UTC, GoZaddy approved these changes
lgtm!

2024-10-28 00:36 UTC, merged